apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: web-app
type: Opaque
stringData:
  username: postgres
  password: password
  host: postgres
  port: "5432"
  db_name: products