apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: web-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: password
  - secretKey: host
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: host
  - secretKey: port
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: port
  - secretKey: db_name
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: db_name