apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
            namespace: web-app

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: web-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: username
      convertFromBase64: true
  - secretKey: password
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: password
      convertFromBase64: true
  - secretKey: host
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: host
      convertFromBase64: true
  - secretKey: port
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: port
      convertFromBase64: true
  - secretKey: db_name
    remoteRef:
      key: fastapi-deployment-db-credentials
      property: db_name
      convertFromBase64: true